services:
  url-backend:
    build:
      context: "../urlshortener-backend/"
      dockerfile: 'Dockerfile'
    volumes:
    - ../urlshortener-backend:/app:cached
    command: ["npx","nodemon", "index.js", "--legacy-watch"]
    networks:
      - team-alpha
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - DATABASE_CONNECTION_STRING=mongodb://admin:admin@mongo:27017/abhishek?authSource=admin
      - FRONTEND_URL=http://localhost:3000

  url-frontend:
    build:
      context: "../urlshortener-frontend/"
      dockerfile: 'Dockerfile'
    volumes:
      - ../urlshortener-frontend:/usr/src/urlshortener-frontend:cached
    networks:
      - team-alpha
    ports:
      - "3000:3000"
    depends_on:
      - url-backend
    environment:
      - CHOKIDAR_USEPOLLING=true 
    command: ["npm", "start"]
  

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks:
      - team-alpha

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: false

    networks:
      - team-alpha

networks:
  team-alpha:
    driver: bridge